version: "3.0"

services:
  mongo-mongodb:
    image: mongo:latest
    container_name: mongo-mongodb
    networks: ["chatui-streaming-api"]

  chatui:
    depends_on:
      - mongo-mongodb
    build:
      context: chatui
      dockerfile: Dockerfile.chatui

    container_name: chatui
    networks: ["chatui-streaming-api"]
    ports:
      - "7070:7070"
    command: npm run dev -- --host 0.0.0.0 --port 7070

networks:
  chatui-streaming-api:
    external: true
