version: "3.3"

services:
  transformers-openai-api:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: transformers-openai-api
    environment:
      - HF_MODEL
      - HOTLOAD
      - TORCH_DTYPE
      - loglevel=DEBUG
      - PYTHONUNBUFFERED=1
      - HF_HUB_ENABLE_HF_TRANSFER=1
      
    volumes:
      - "./app:/home/ubuntu/app"
      - "./huggingface:/home/ubuntu/.cache/huggingface"
    ports:
      - "7088:7088"
    command: ~/.local/bin/uvicorn app.main:app --host 0.0.0.0 --port 7088 --reload --reload-dir ./app