version: "3.3"

services:
  chatui-streaming-api:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: chatui-streaming-api
    networks: ["chatui-streaming-api"]
    environment:
      - HF_MODEL
      - HOTLOAD
      - TORCH_DTYPE
      - loglevel=DEBUG
      - PYTHONUNBUFFERED=1
      
    volumes:
      - "./app:/home/ubuntu/app"
      - "./huggingface:/home/ubuntu/.cache/huggingface"
    ports:
      - "7075:7075"
    command: ~/.local/bin/uvicorn app.main:app --host 0.0.0.0 --port 7075 --reload --reload-dir ./app

networks:
  chatui-streaming-api:
    external: true