version: "3.3"

services:
  transformers-openai-api:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: transformers-openai-api
    environment:
      - HF_MODEL
      - HOTLOAD
      - TORCH_DTYPE
      - ARCHITECTURE_TYPE
      - MODEL_TYPE
      - TOKENIZER_TYPE
      - TOKENIZER_USE_FAST
      - ATTN_IMPLEMENTATION
      - CACHE_TYPE
      - loglevel=DEBUG
      - PYTHONUNBUFFERED=1
      - HF_HUB_ENABLE_HF_TRANSFER=1
      
    volumes:
      - "./transformers_openai:/home/ubuntu/transformers_openai"
      - "./huggingface:/home/ubuntu/.cache/huggingface"
    ports:
      - "7088:7088"
    command: python3 -m transformers_openai.main --host 0.0.0.0 --port 7088 --reload true